Dave/Dave/urls.py
# Dave URL Configuration
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.views.generic.base import RedirectView
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('', RedirectView.as_view(url="")),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]+ static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

Dave/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic.base import RedirectView
from .views import *

app_name = 'blog'
urlpatterns = [

    # Main Navbar
    path('contact-me/', contactUs, name='contact'),
    # path('blog/subscribe/',subscribeNews, name='subscribenews'),
    path('', HomeView.as_view(), name='home'),
    # path('expertise/digital_marketing',views.ExpertiseView.as_view(), name='expertise'),
    path('expertise/digital_marketing/', expertiseView, name='expertise'),
    # path('agency/',AgencyView.as_view(),name='agency'),
    path('agency/', agencyView, name='agency'),
    # path('portfolio/photography', PortfolioView.as_view(), name='portfolio'),
    path('portfolio/photography/', portfolioView, name='portfolio'),
    path('products/', productsView, name='products'),
    path('blog/', BlogViews, name='post'),
    path('connect/', ConnectView.as_view(), name='connect'),
    path('letsconnect/', letsConnect, name='letsconnect'),
    # path('letsconnect/',letsConnect,name='letsconnect'),


    #  ExpertiseSubViews
    path('expertise/digital_marketing/',
         ExpertiseSubView.as_view(), name='digital_marketing'),
    path('expertise/ui_ux/', ExpertiseSub1View, name='ui_ux'),
    path('expertise/gaming/', ExpertiseSub2View, name='gamming'),
    path('expertise/seo/', ExpertiseSub3View, name='seo'),
    path('expertise/logo_creator/',
         ExpertiseSub4View, name='logo_creator'),
    path('expertise/web_development/',
         ExpertiseSub5View, name='web_developer'),

    # PortfolioSubViews
    path('portfolio/photography/', PortfolioSub1View.as_view(), name='photography'),
    path('portfolio/logo_design/', PortfolioSub2View, name='logo_design'),
    path('portfolio/web_design/', PortfolioSub3View, name='web_design'),
    path('portfolio/vfx/', PortfolioSub4View, name='vfx'),
    path('portfolio/animations/', PortfolioSub5View, name='animations'),
    path('portfolio/xyz/', PortfolioSub6View, name='xyz'),






    path('blog/<slug:slug>/', BlogDetail, name='detail'),
    path('search/', searchPost, name='search'),

]

# url(r'^ckeditor/', include('ckeditor_uploader.urls')),

Dave/blog/models.py
from django.db import models
# from ckeditor_uploader.fields import RichTextField
from django.core.validators import RegexValidator, MinValueValidator
from ckeditor_uploader.fields import RichTextUploadingField
#
# from taggit.managers import TaggableManager


class Blog(models.Model):
    Title = models.CharField(max_length=200)
    Image = models.ImageField()
    Content = RichTextUploadingField(blank=True)
    Tag = models.CharField(max_length=200)
    imageHeading = models.CharField(max_length=220, null=True)
    Slug = models.SlugField(max_length=200, unique=True)
    Date = models.DateField(auto_now_add=True)
    ###############################################################################
    # tags = TaggableManager()

    class Meta:
        ordering = ('-Date', '-pk',)

    def __str__(self):
        return self.Title

    def __unicode__(self):
        return u'%s' % self.Title


class Comment(models.Model):
    Post = models.ForeignKey(
        Blog, on_delete=models.CASCADE, related_name='comments')
    Name = models.CharField(max_length=100)
    Email = models.EmailField(max_length=254)
    Body = models.TextField()
    Created = models.DateTimeField(auto_now_add=True)
    Active = models.BooleanField(default=True)
    Parent = models.ForeignKey(
        'self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')

    class Meta:
        ordering = ('-Created',)

    def __str__(self):
        return ('Comment By {}'.format(self.Name))


class Contact(models.Model):
    name = models.CharField(max_length=55, default='')
    email = models.EmailField(max_length=255)
    phone_no = models.IntegerField(validators=[RegexValidator(
        "^0?[5-9]{1}\d{9}$")], null=True, blank=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return self.name


class SubscribeNewsletter(models.Model):
    subscriberemail = models.EmailField(max_length=255)

    def __str__(self):
        return self.subscriberemail


class LetsConnect(models.Model):
    firstname = models.CharField(max_length=55, default='')
    lastname = models.CharField(max_length=55, default='')
    lc_email = models.EmailField(max_length=255)
    lc_phone_no = models.IntegerField(validators=[RegexValidator(
        "^0?[5-9]{1}\d{9}$")], null=True, blank=True)
    lc_message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-pk']

    def __str__(self):
        return self.firstname

Dave/blog/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404, HttpResponseRedirect
from .models import *
from .form import *
from django.views.generic.base import TemplateView
from django.contrib import messages
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# class BaseView(TemplateView):
#     template_name = "base.html"

class HomeView(TemplateView):
    template_name = "blog/home.html"


def expertiseView(request):
    posts = Blog.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/expertise/digital_marketing.html', context)
# class ExpertiseView(TemplateView):
#     template_name = "blog/expertise/digital_marketing.html"


def agencyView(request):
    posts = Blog.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/agency.html', context)
# class AgencyView(TemplateView):
#     model = Blog
#     post = Blog.objects.all()
#     template_name = "blog/agency.html"


def portfolioView(request):
    posts = Blog.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/portfolio/photography.html', context)
# class PortfolioView(TemplateView):
#     template_name = "blog/portfolio/photography.html"


def productsView(request):
    posts = Blog.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/products.html', context)
# class PortfolioView(TemplateView):
#     template_name = "blog/portfolio/photography.html"


class ConnectView(TemplateView):
    template_name = "blog/letsconnect.html"


# Expertise sub page views
class ExpertiseSubView(TemplateView):
    model = Contact
    template_name = "blog/expertise/digital_marketing.html"


# class ExpertiseSub1View(TemplateView):
#     model = Contact
#     template_name = "blog/expertise/ui_ux.html"


def ExpertiseSub1View(request):
    posts = Blog.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/expertise/ui_ux.html', context)


# class ExpertiseSub2View(TemplateView):
#     model = Contact
#     template_name = "blog/expertise/gaming.html"


def ExpertiseSub2View(request):
    posts = Blog.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/expertise/gaming.html', context)


# class ExpertiseSub3View(TemplateView):
#     model = Contact
#     template_name = "blog/expertise/seo.html"


def ExpertiseSub3View(request):
    posts = Blog.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/expertise/seo.html', context)


# class ExpertiseSub4View(TemplateView):
#     model = Contact
#     template_name = "blog/expertise/logo_creator.html"


def ExpertiseSub4View(request):
    posts = Blog.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/expertise/logo_creator.html', context)


# class ExpertiseSub5View(TemplateView):
#     model = Contact
#     template_name = "blog/expertise/web_development.html"


def ExpertiseSub5View(request):
    posts = Blog.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/expertise/web_development.html', context)


# PORTFOLIO SUB VIEWS
class PortfolioSub1View(TemplateView):
    template_name = "blog/portfolio/photography.html"


# class PortfolioSub2View(TemplateView):
#     template_name = "blog/portfolio/logo_design.html"


def PortfolioSub2View(request):
    posts = Blog.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/portfolio/logo_design.html', context)


# class PortfolioSub3View(TemplateView):
#     template_name = "blog/portfolio/web_design.html"

def PortfolioSub3View(request):
    posts = Blog.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/portfolio/web_design.html', context)

# class PortfolioSub4View(TemplateView):
#     template_name = "blog/portfolio/vfx.html"


def PortfolioSub4View(request):
    posts = Blog.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/portfolio/vfx.html', context)

# class PortfolioSub5View(TemplateView):
#     template_name = "blog/portfolio/animations.html"


def PortfolioSub5View(request):
    posts = Blog.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/portfolio/animations.html', context)

# class PortfolioSub6View(TemplateView):
#     template_name = "blog/portfolio/xyz.html"


def PortfolioSub6View(request):
    posts = Blog.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blog/portfolio/xyz.html', context)


def BlogViews(request):
    post = Blog.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(post, 6)
    if request.method == 'POST':
        subscriberemail = request.POST.get('subscriberemail')
        if len(subscriberemail) < 8:
            messages.error(request, 'Please fill the form correctly.')
        else:
            messages.success(
                request, 'Your message has been successfully sent.')
            subscribenews = SubscribeNewsletter(
                subscriberemail=subscriberemail)
            subscribenews.save()
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {
        'posts': posts
    }
    return render(request, 'blog/blog.html', context)


def BlogDetail(request, slug):
    posts = Blog.objects.all()
    post = get_object_or_404(Blog, Slug=slug)
    # Tag = get_object_or_404(Blog, Slug = slug)
    # Tags = Blog.Tag.similar_objects()
    comments = post.comments.filter(Active=True, Parent__isnull=True)

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            Parent_obj = None
            try:
                Parent_id = int(request.POST.get('Parent_id'))
            except:
                Parent_id = None
            if Parent_id:
                Parent_obj = Comment.objects.get(id=Parent_id)
                if Parent_obj:
                    reply_comment = comment_form.save(commit=False)
                    reply_comment.Parent = Parent_obj
            new_comment = comment_form.save(commit=False)
            new_comment.Post = post
            new_comment.save()
            return redirect('blog:detail', slug)

    else:
        comment_form = CommentForm()

    if request.method == 'POST':
        subscriberemail = request.POST.get('subscriberemail')
        if len(subscriberemail) < 8:
            messages.error(request, 'Please fill the form correctly.')
        else:
            messages.success(
                request, 'Your message has been successfully sent.')
            subscribenews = SubscribeNewsletter(
                subscriberemail=subscriberemail)
            subscribenews.save()
    context = {
        'posts': posts,
        'blog': post,
        'comments': comments,
        'comment_form': comment_form,
        # 'Tag':Tag,
        # 'Tags':Tags
    }
    return render(request, 'blog/blogdetail.html', context)

# def baseBlog(request):
#     post = Blog.objects.all()
#     context = {
#         'post' : post
#     }
#     return render(request,'base.html',context)


def contactUs(request):
    print("Hello")
    post = Blog.objects.all()
    url = ''
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        phone = request.POST['phone']
        message = request.POST['message']
        url = request.POST['url']
        if len(email) < 3 or len(phone) < 10 or len(message) < 4:
            messages.error(request, 'Please fill the form correctly.')
        else:
            messages.success(
                request, 'Your message has been successfully sent.')
        contact = Contact(name=name, email=email,
                          phone_no=phone, message=message)
        contact.save()
        return HttpResponseRedirect(url)
    context = {
        'post': post
    }
    return HttpResponseRedirect(url)


def letsConnect(request):
    print("Hello")
    connect = LetsConnect.objects.all()
    if request.method == 'POST':
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        lc_email = request.POST['lc_email']
        lc_phone = request.POST['lc_phone']
        lc_message = request.POST['lc_message']
        if len(lc_email) < 3 or len(lc_phone) < 10 or len(lc_message) < 4:
            messages.error(request, 'Please fill the form correctly.')
        else:
            messages.success(
                request, 'Your message has been successfully sent.')
        letsconnect = LetsConnect(firstname=firstname, lastname=lastname,
                                  lc_email=lc_email, lc_phone_no=lc_phone, lc_message=lc_message)
        letsconnect.save()
        return redirect('/letsconnect')
    context = {
        'connect': connect
    }
    return render(request, './blog/letsconnect.html', context)


def searchPost(request):
    context = {}
    if request.GET:
        query = request.GET.get('q', '')
        context['query'] = str(query)

    post = Blog.objects.filter(
        Q(Title__icontains=query) | Q(
            Content__icontains=query) | Q(Tag__icontains=query)
    ).distinct()

    if post.count == 0:
        messages.warning(request, 'NO search Results')

    parms = {
        'post': post,

Dave/blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <title>Portfolio</title>
  <link rel="stylesheet" href="{% static './css/base.css' %}" />
  <link rel="stylesheet" href="{% static './css/header.css' %}" />
  <link rel="stylesheet" href="{% static './css/contact.css' %}" />
  <!-- <link rel="stylesheet" href="{% static 'css/expertise.css' %}"> -->
</head>


<body>
    <div class="base_header_nav">
  <!-- Navigation Bar -->
  <header class="header">
    <a href="/" class="text1 logo">LOGO</a>
    <input class="menu-btn" type="checkbox" id="menu-btn" />
    <label class="menu-icon" for="menu-btn"><span class="navicon"></span></label>
    {% with request.resolver_match.url_name as url_name %}
    <!-- {% with my_array="digital_marketing ui_ux gaming seo logo_creator web_development" %}
        {% for i in my_array.split %}    
            {% if i in my_array.split %}
            <li class="{% if url_name == '{{i}}' %} active {% endif %}"><a class="text1 expertise "
                href="/expertise/{{i}}">EXPERTISE{{i}}</a></li>
            {% endif %} 
        {% endfor%}
    {% endwith %} -->
    <ul class="menu menu1">
      <li class="{% if url_name == 'home' %} active {% endif %}"><a class="text1 home "
          href="/">HOME</a></li>
      <li class="{% if url_name == 'expertise' %} active {% endif %}"><a class="text1 expertise"
          href="/expertise/digital_marketing">EXPERTISE</a></li>
      <li class="{% if url_name == 'agency' %} active {% endif %}"><a class="text1 agency"
          href="/agency">AGENCY</a></li>
      <li class="{% if url_name == 'portfolio' %} active {% endif %}"><a class="text1 portfolio"
          href="/portfolio/photography">WORK</a></li>
      <li class="{% if url_name == 'products' %} active1 {% endif %}"><a class="text1" href="/products">PRODUCTS</a></li>

      <li class="{% if url_name == 'post' %} active {% endif %}"><a class="text1 post"
          href="{%  url 'blog:post' %}">BLOG</a></li>
      <li class="{% if url_name == 'letsconnect' %} active {% endif %}"><a class="text1 connect"
          href="/letsconnect">LET'S CONNECT</a></li>
    </ul>
    {% endwith %}
    <hr class="hrline">    
</header>
</div>

    
    {% block content %}
    {% endblock %}

    <div class="base_contact">
    <section class="contact" id="connect">
      <div class="container1">
      <div class="left1">
          <div class="news">
          <h6>LATEST NEWS</h6>
          <br> 
            {% for p in posts|slice:":2" %}
                <a href="{% url 'blog:detail' slug=p.Slug %}"><p class="news-title">{{p.Title}}</p></a> 
                <p>{{p.Tag}}</p>
                <br>
            {% endfor %}
          </div>
          <div class="expfoot">
          <h6>EXPERTISE</h6>
          <div class="explist">
              <p>DIGITAL MARKETING</p>
              <p>DIGITAL MARKETING</p>
              <p>DIGITAL MARKETING</p>
              <p>DIGITAL MARKETING</p>
              <p>DIGITAL MARKETING</p>
          </div>
          </div>
          <div class="contfoot">
          <h6>CONTACT US</h6>
          </div>
      </div>
      <div class="right1">
          <div class="contactform">
          <div class="contacttext">
              <h2 id="head1">DO YOU HAVE ANY </h2>
              <h2 id="head2">START UP</h2>
              <h2 id="head3">IDEA?</h2>
          </div>
          <div class="contactin">
              <form action="/contact-me/" method="POST" id="contact-form">
              {% csrf_token %}
              <input type="text" name='name' placeholder="Enter your name"><br>
              <input type="email" name='email' placeholder="Email Address"><br>
              <input type="phone" name='phone' placeholder="Mobile Number"><br>
              <input type="text" name='message' placeholder="Query"><br>
              <input type="hidden" name="url" id="inp-url">
              <button class="button_submit" type="submit" onclick="submitForm()">Submit</button>
              </form>
          </div>
          </div>
      </div>
      </div>
  </section>
</div>
<script>

function submitForm() {
    let x = window.location.href.split("/")[3];
    let y = window.location.href.split("/")[4];
    let inp = document.getElementById("inp-url");
    if (y === "") {
        inp.setAttribute("value", `/${x}`);
    }
    inp.setAttribute("value", `/${x}/${y}`);
}

</script>

</body>

</html>